<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>
<form class="width_100" action="<?= $variables['purchase']['purchasing']['formAction'] ?>" method="post">
	<input type="hidden" name="cmd" value="_xclick" />
	<input type="hidden" name="business" value="<?= $variables['purchase']['purchasing']['paypalemail'] ?>" />
	<input type="hidden" name="item_name" value="Payment for order #<?= $variables['purchase']['purchasing']['order_id'] ?>" />
	<input type="hidden" name="item_number" value="<?= $variables['purchase']['purchasing']['order_id'] ?>" />
	<input type="hidden" name="amount" value="<?= $variables['purchase']['purchasing']['total'] ?>" />
	<input type="hidden" name="no_shipping" value="1" />
	<input type="hidden" name="return" value="<?= $variables['purchase']['purchasing']['return_success'] ?>" />
	<input type="hidden" name="rm" value="2" />
	<input type="hidden" name="cancel_return" value="<?= $variables['purchase']['purchasing']['cancel_return'] ?>" />
	<input type="hidden" name="notify_url" value="<?= $variables['purchase']['purchasing']['notify_url'] ?>" />
	<input type="hidden" name="currency_code" value="<?= $variables['purchase']['purchasing']['currency'] ?>" />

	<div>
		<?= $this->translate('payment-redirect-text') . 'PayPal.' ?> PayPal.
	</div>

	<div>
		<input type="submit" value="<?= $this->translate('pay') ?>" class="button big"/>
	</div>
</form>
<?=$this->render(array(), 'emarket/payment/form-send')?>
