<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>
<form id="form_yandex30" action="<?= $variables['purchase']['purchasing']['formAction'] ?>" method="post">
	<input type="hidden" name="shopId" value="<?= $variables['purchase']['purchasing']['shopId'] ?>" />
	<input type="hidden" name="Sum" value="<?= $variables['purchase']['purchasing']['Sum'] ?>" />
	<input type="hidden" name="BankId" value="<?= $variables['purchase']['purchasing']['BankId'] ?>" />
	<input type="hidden" name="scid" value="<?= $variables['purchase']['purchasing']['scid'] ?>" />
	<input type="hidden" name="CustomerNumber" value="<?= $variables['purchase']['purchasing']['CustomerNumber'] ?>" />
	<input type="hidden" name="order-id" value="<?= $variables['purchase']['purchasing']['orderId'] ?>" />

	<?php
	if (isset($variables['purchase']['purchasing']['ym_merchant_receipt'])) {
		$merchantReceipt = $variables['purchase']['purchasing']['ym_merchant_receipt'];
		echo <<<HTML
	<input type="hidden" name="ym_merchant_receipt" value="$merchantReceipt" />
HTML;
	}
	?>

	<input type="hidden" name="PaymentType" value="" />
	<input type="hidden" name="PaymentTypeProvider" value="" />
	<input type="hidden" name="cms_name" value="umistand"/>
	<div class="inline">
		<?php
			if (isset($variables['purchase']['void:mode_type_list']) && is_array($variables['purchase']['void:mode_type_list'])) {
				foreach ($variables['purchase']['void:mode_type_list'] as $item) {
					$id = (isset($item['id'])) ? $item['id'] : '';
					$type = (isset($item['type'])) ? $item['type'] : '';
					$subType = (isset($item['subtype'])) ? $item['subtype'] : '';
					$label = (isset($item['subtype'])) ? $item['label'] : '';
					echo <<<HTML
<label>
	<input type="radio" name="mode_type" value="$id" onChange="javascript:change('$type', '$subType');"/>
	$label
</label>
HTML;
				}
			}
		?>
	</div>

	<div>
		<?= $this->translate('payment-redirect-text') . 'Yandex.' ?> Yandex.
	</div>

	<div>
		<input type="submit" value="<?= $this->translate('pay') ?>" class="button big"/>
	</div>
</form>
<script>
	var elements = document.getElementById('form_yandex30').elements;
	elements.mode_type.value = '';
	function change(type, subtype) {
		elements.PaymentType.value = type;
		elements.PaymentTypeProvider.value = subtype;
	}
</script>
<?=$this->render(array(), 'emarket/payment/form-send')?>
