<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>

<h1 umi:element-id="<?=$variables['full:page']->getId()?>" umi:field-name="h1" umi:empty="<?=$this->translate('empty-page-name')?>"><?=$variables['full:page']->getValue('h1')?></h1>

<div umi:element-id="<?=$variables['@pageId']?>" umi:field-name="content" umi:empty="<?=$this->translate('empty-page-content')?>">
    <?=$variables['full:page']->getValue('content')?>
</div>

<?=$this->render($this->macros('news', 'related_links'), 'news/relatedlinks') ?>

<a href="../">
    <?=$this->translate('news-back')?>
</a>
<div class="social">
    <div class="plusone">
        <div class="g-plusone" data-size="small" data-count="true"></div>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function(){ jQuery.getScript('//yandex.st/share/share.js', function() {
            new Ya.share({
                'element': 'ya_share1',
                'elementStyle': {
                    'type': 'button',
                    'linkIcon': true,
                    'border': false,
                    'quickServices': ['yaru', 'vkontakte', 'facebook', 'twitter', 'odnoklassniki', 'moimir', 'lj']
                },
                'popupStyle': {
                    'copyPasteField': true
                }
            });
        });
        });
    </script>
    <span id="ya_share1"></span>
</div>

