<?php
/** @var umiTemplaterPHP $this */
/** @var array $variables */
?>


<?php if($variables): ?>
    <a
        href="<?=$variables['attribute:link']?>"
        umi:empty="<?=$this->translate('comment-title')?>"
        umi:field-name="name"
        umi:element-id="<?=$variables['attribute:id']?>"
    >
        <?=$variables['attribute:name']?>
    </a>
    <?=$this->render(array('page' => $this->getPageById($variables['attribute:id'])), 'forum/conf_last_message') ?>
<?php endif ?>