<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>

<a name="add-comment"></a>
<form method="post" action="<?=$variables['add_form']['action']?>">
    <div class="form_element">
        <label>
            <span><?=$this->translate('comment-body')?>:</span>
            <textarea name="comment"></textarea>
        </label>
    </div>
    <div class="form_element">
        <input type="submit" class="button" value="<?=$this->translate('comment-submit')?>" />
    </div>
</form>