<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>

<?php if (isset($variables['attribute:type'])): ?>
    <hr /><a name="comments"></a>
    <h4><?=$this->translate('comments')?> Facebook:</h4>
    <div id="fb-root"></div>
    <script src="http://connect.facebook.net/ru_RU/all.js#xfbml=1"></script>
    <fb:comments href="<?='//' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']?>" num_posts="<?=$variables['per_page']?>" width="<?=$variables['width']?>" colorscheme="<?=$variables['colorscheme']?>"></fb:comments>
<?php endif; ?>