<?php
/** @var umiTemplaterPHP $this */
/** @var array $variables */
?>

<?php $registrate = $this->macros('users', 'registrate') ?>

<h1><?= $variables['@header'] ?></h1>

<form id="registrate" enctype="multipart/form-data" method="post" action="<?= cmsController::getInstance()->getPreLang() ?>/users/registrate_do/" onsubmit="site.forms.data.save(this); return site.forms.data.check(this);">
    <div>
        <label class="required">
            <span>
                <?= $this->translate('login') ?>:
            </span>
            <input type="text" name="login" class="textinputs" />
        </label>
    </div>
    <div>
        <label class="required">
            <span>
                <?= $this->translate('password') ?>:
            </span>
            <input type="password" name="password" class="textinputs" />
        </label>
    </div>
    <div>
        <label class="required">
            <span>
                <?= $this->translate('password-confirm') ?>:
            </span>
            <input type="password" name="password_confirm" class="textinputs" />
        </label>
    </div>
    <div>
        <label class="required">
            <span>
                <?= $this->translate('e-mail') ?>:
            </span>
            <input type="text" name="email" class="textinputs" />
        </label>
    </div>

    <?=$this->render($this->macros('system', 'captcha'), 'library/captcha')?>

    <div>
        <input type="submit" class="button" value="<?= $this->translate('registration-do') ?>" />
    </div>
</form>
