<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>

<?php if (isset($variables['add-link'])): ?>
    <a href="<?=$variables['add-link']?>" class="compare">
        <?=$this->translate('compare-add')?>
    </a>
<?php endif;?>

<?php if (isset($variables['del-link'])): ?>
    <a href="<?=$variables['del-link']?>" class="compare">
        <?=$this->translate('compare-del')?>
    </a>
<?php endif;?>